DELETE http://localhost:4000/api/site/642aee4c52d148b9de95d4d0
Content-Type: application/json

{
    "siteName": "New Site",
    "location": "Some location",
    "country": "Some country",
    "city": "Some city",
    "managerInformation": {
      "fullName": "John Doe",
      "emailAddress": "johndoe@example.com",
      "contact": "1234567890",
      "status": "Enabled"
}
}
###

PUT http://localhost:4000/api/site/642af31e887a5060fd5ab048
Content-Type: application/json

{
  "siteName": "New Sites",
  "location": "Some locations",
  "country": "Some countrys",
  "city": "Some city",
  "managerInformation": {
    "fullName": "John Doed",
    "emailAddress": "johndoe@example.com",
    "contact": "1234567890",
    "status": "Enabled"
  }
}


###

GET http://localhost:4000/api/site
Content-Type: application/json

{
    "siteName": "New Site",
    "location": "Some location",
    "country": "Some country",
    "city": "Some city",
    "managerInformation": {
      "fullName": "John Doe",
      "emailAddress": "johndoe@example.com",
      "contact": "1234567890",
      "status": "Enabled"
      }
}

###

GET http://localhost:4000/api/site/642aee4752d148b9de95d4ce


###

POST http://localhost:4000/api/department
Content-Type: application/json

{
    "department": "New Department2",
    "status" : "Enabled"
}